---
- hosts: 172.31.20.250
  become: yes
  tasks:
   - name: I want to execute linux command 
     command: hostname -f
     register: myresult 

   - name: I want to display my fisrs task result 
     debug:
      msg: "{{myresult}}"