---
- hosts: 172.31.26.218
  become: yes
  tasks:
  - name: I want to execute linux command 
    command: hostsname -f
    resister: myresult 

  - name: I want to display my fisrs task result 
    debug:
     msg: "{{myresult}}"