---
- hosts: 172.31.26.218
  become: yes
  tasks:
  - name: i want to create a file om ubuntu node
    file:
     path: /home/ubuntu/mytestfile
     state: touch
     owner: umesh
    register: myresult

    debug:
     msg: "{{myresult}}" 