---
- hosts: 172.31.26.218
  become: yes
  tasks: 
  - name: I want to install git 
    apt:
     name: git
     state: present
    tags: mygit
  - name: I want to install wget
    apt:
     name: wget
     state: present 
    tags: mywget
  - name: I want to install tree
    apt: 
     name: tree
     state: present
    tags: mytree